title: The Writing of MMMoeller
name: Madilyn Moeller
email: mmmoellerwriter@gmail.com
description: This site contains a sample of works written or contributed to by Madilyn Moeller, along with her resume and biographical information. Contact the author below.

baseurl: "/blog"
url: ""

display_footer: none  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: HHC Website
project_one_description: Spring 2020 Professional Writing majors worked together in Dr. McKee's capstone to create a brochure and <a href="http://historichopewellchurch.org">website</a> for the Historic Hopewell Church, located in College Corner, OH. Specific contributions were for the history team and webpages 1916-1961, 1962-Present.
project_one_url: http://historichopewellchurch.org
project_one_icon: location_on

project_two: Scarlet Letter ebook
project_two_description: In a small team, Madilyn added HTML5, CSS, semantic content, and compiled the book for Project Gutenberg as an assignment for Dr. Lockridge's digital publishing class. All work was done remotely.
project_two_url: https://github.com/timlockridge/digpub-the-scarlet-letter
project_two_icon: photo_camera


project_three: Genre Exploration
project_three_description: For Dr. Mauk's rhetoric capstone, Madilyn researched the origin, evolution, and cultural significance of self-help books.
project_three_url: https://docs.google.com/presentation/d/1shCxCVyDGSB1z5uVoWTs1kRVTT7-adhskuFmQonlA40/edit?usp=sharing
project_three_icon: hotel


project_four: Grant Proposal
project_four_description: In Dr. Quinn's neuroscience capstone, Madilyn designed a research study and wrote a grant proposal and presentation to support it.
project_four_url: https://docs.google.com/presentation/d/1DO-UVUk7kp1dqZjarQzPjDMxCdpsW9J0Noq816ZRo4c/edit?usp=sharing
project_four_icon: restaurant

project_five: Neurology & Language
project_five_description: In linguistics, Madilyn chose to study the junction between her focus areas: the perisylvian region.
project_five_url: https://drive.google.com/file/d/1YQMrCtN5sdOoiwwUBgoZtJFVlhTvGeJI/view?usp=sharing
project_five_icon: coffee-unsplash

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
#  - name: amazonwebservices
#  - name: android
#  - name: angularjs
#  - name: apache
#  - name: appcelerator
  - name: apple
#  - name: atom
#  - name: babel
#  - name: backbonejs
#  - name: bitbucket
#  - name: bootstrap
#  - name: bower
#  - name: c
  - name: chrome
#  - name: codeigniter
#  - name: coffescript
#  - name: confluence
#  - name: cplusplus
#  - name: csharp
  - name: css3
#  - name: cucumber
#  - name: d3js
#  - name: debian
#  - name: devicon
#  - name: django
#  - name: docker
#  - name: doctrine
#  - name: dot-net
#  - name: drupal
#  - name: erlang
  - name: facebook
  - name: firefox
#  - name: foundation
#  - name: gatling
#  - name: gimp
#  - name: git
  - name: github
#  - name: gitlab
#  - name: go
  - name: google
#  - name: gradle
#  - name: grunt
#  - name: gulp
 # - name: heroku
  - name: html5
#  - name: ie10
  - name: illustrator
#  - name: inkscape
#  - name: itellij
#  - name: java
#  - name: jasmine
#  - name: javascript
#  - name: laravel
#  - name: less
#  - name: linux
#  - name: meteor
#  - name: mocha
#  - name: mongodb
#  - name: moodle
#  - name: mysql
#  - name: nginx
#  - name: nodejs
#  - name: nodewebkit
#  - name: oracle
  - name: photoshop
#  - name: php
#  - name: phpstorm
 # - name: protractor
 # - name: postgresql
 # - name: python
  #- name: pycharm
 # - name: rails
 # - name: react
 # - name: redhat
  #- name: redis
 # - name: ruby
 # - name: rubymine
  - name: safari
 # - name: sass
 # - name: sequelize
  - name: slack
 # - name: sourcetree
 # - name: ssh
#  - name: swift
#  - name: symfony
#  - name: tomcat
#  - name: travis
  - name: trello
  - name: twitter
#  - name: typescript
#  - name: ubuntu
#  - name: vim
  - name: visualstudio
 # - name: vuejs
 # - name: webpack
 # - name: webstorm
  - name: windows8
  - name: wordpress
#  - name: yii
 # - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Explore

github: https://github.com/mmmoeller
upwork: https://upwork.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://mmmoeller.github.io/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
